# Generated by Django 5.2.4 on 2026-10-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer')], max_length=50, verbose_name='Payment Gateway'),
        ),
    ]
