# Generated by Django 5.2.4 on 2026-09-29 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_image_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Red, Navy Blue', max_length=50, unique=True)),
                ('hex_code', models.CharField(blank=True, help_text='e.g., #FF0000', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Colors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., S, M, L, XL, XXL', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='e.g., Small, Medium, Large', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='For ordering sizes')),
            ],
            options={
                'verbose_name_plural': 'Sizes',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False, help_text='Whether this product has size/color variants'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price (used if no variant price set)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Total stock across all variants (auto-calculated)'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Variant-specific price (overrides product base price)', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.size')),
            ],
            options={
                'ordering': ['size__sort_order', 'color__name'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='products_pr_product_66459e_idx'), models.Index(fields=['stock'], name='products_pr_stock_c72f45_idx')],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
