# Generated by Django 5.2.4 on 2026-10-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_resync_product_variant_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='display_name',
            field=models.CharField(help_text='e.g., Small, Medium, Large, 6, 7, 8', max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(help_text='e.g., S, M, L, XL, 6, 7, 8', max_length=50, unique=True),
        ),
    ]
